/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/access/reset-password': RouteRecordInfo<'/access/reset-password', '/access/reset-password', Record<never, never>, Record<never, never>>,
    '/access/signin': RouteRecordInfo<'/access/signin', '/access/signin', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/database': RouteRecordInfo<'/database', '/database', Record<never, never>, Record<never, never>>,
    '/docs/background': RouteRecordInfo<'/docs/background', '/docs/background', Record<never, never>, Record<never, never>>,
    '/factory/': RouteRecordInfo<'/factory/', '/factory', Record<never, never>, Record<never, never>>,
    '/insight-rules': RouteRecordInfo<'/insight-rules', '/insight-rules', Record<never, never>, Record<never, never>>,
    '/members': RouteRecordInfo<'/members', '/members', Record<never, never>, Record<never, never>>,
    '/park/': RouteRecordInfo<'/park/', '/park', Record<never, never>, Record<never, never>>,
    '/system/auth': RouteRecordInfo<'/system/auth', '/system/auth', Record<never, never>, Record<never, never>>,
    '/system/role': RouteRecordInfo<'/system/role', '/system/role', Record<never, never>, Record<never, never>>,
    '/system/user': RouteRecordInfo<'/system/user', '/system/user', Record<never, never>, Record<never, never>>,
  }
}
